# Generated by Django 6.1.1 on 2026-09-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
