# Generated by Django 6.1.1 on 2026-09-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_assigned_to_complaint_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolutions/'),
        ),
    ]
