# Generated by Django 6.1.1 on 2026-09-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_resolution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sla_hours',
            field=models.PositiveIntegerField(default=48),
        ),
    ]
