# Generated by Django 6.1.1 on 2026-09-12 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_tracking_token_complaintfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
